spring.profiles.active: jirachai
---
spring:
  profiles: local
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/emitter?useUnicode=true&characterEncoding=UTF-8
    username: root 
    password: manager
  jpa:
    database: MYSQL
    show-sql: true
    hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
    encoding: UTF-8
---
spring:
  profiles: jirachai
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/dinner_dash?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password:
  jpa:
    database: MYSQL
    show-sql: true
    hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
    encoding: UTF-8
security:
  basic:
    enabled: false 
server:
    port: 1080